/**
 * NIS2 Recommendations per Category
 *
 * Each category has 2 prioritized recommendations with concrete first steps,
 * legal references, and BSI IT-Grundschutz building block references.
 *
 * Legal basis: §30 BSIG (BGBl. 2025 I Nr. 301)
 * BSI references: IT-Grundschutz-Kompendium Edition 2023
 */

import type { Recommendation } from './types';

export const RECOMMENDATIONS: Recommendation[] = [
  // Category 1: Risikoanalyse
  {
    id: 'rec-ra-1',
    categoryId: 'risk-analysis',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'recommendations.ra1.title',
    descriptionKey: 'recommendations.ra1.description',
    firstStepKey: 'recommendations.ra1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. a NIS2-RL, §30 Abs. 2 Nr. 1 BSIG',
    bsiReference: 'BSI-Standard 200-3, ISMS.1',
  },
  {
    id: 'rec-ra-2',
    categoryId: 'risk-analysis',
    priority: 'medium',
    effortLevel: 'quick',
    titleKey: 'recommendations.ra2.title',
    descriptionKey: 'recommendations.ra2.description',
    firstStepKey: 'recommendations.ra2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. a NIS2-RL, §30 Abs. 2 Nr. 1 BSIG',
    bsiReference: 'ORP.1, ISMS.1',
  },
  // Category 2: Sicherheitsvorfälle
  {
    id: 'rec-ih-1',
    categoryId: 'incident-handling',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'recommendations.ih1.title',
    descriptionKey: 'recommendations.ih1.description',
    firstStepKey: 'recommendations.ih1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. b NIS2-RL, §30 Abs. 2 Nr. 2 BSIG',
    bsiReference: 'DER.2.1, BSI-Standard 100-4',
  },
  {
    id: 'rec-ih-2',
    categoryId: 'incident-handling',
    priority: 'medium',
    effortLevel: 'quick',
    titleKey: 'recommendations.ih2.title',
    descriptionKey: 'recommendations.ih2.description',
    firstStepKey: 'recommendations.ih2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. b NIS2-RL, §30 Abs. 2 Nr. 2 BSIG',
    bsiReference: 'DER.2.1, OPS.1.1.5',
  },
  // Category 3: Betriebskontinuität
  {
    id: 'rec-bc-1',
    categoryId: 'business-continuity',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'recommendations.bc1.title',
    descriptionKey: 'recommendations.bc1.description',
    firstStepKey: 'recommendations.bc1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. c NIS2-RL, §30 Abs. 2 Nr. 3 BSIG',
    bsiReference: 'CON.3, BSI-Standard 200-4',
  },
  {
    id: 'rec-bc-2',
    categoryId: 'business-continuity',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'recommendations.bc2.title',
    descriptionKey: 'recommendations.bc2.description',
    firstStepKey: 'recommendations.bc2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. c NIS2-RL, §30 Abs. 2 Nr. 3 BSIG',
    bsiReference: 'DER.4, BSI-Standard 200-4',
  },
  // Category 4: Lieferkette
  {
    id: 'rec-sc-1',
    categoryId: 'supply-chain',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'recommendations.sc1.title',
    descriptionKey: 'recommendations.sc1.description',
    firstStepKey: 'recommendations.sc1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. d NIS2-RL, §30 Abs. 2 Nr. 4 BSIG',
    bsiReference: 'ORP.1',
  },
  {
    id: 'rec-sc-2',
    categoryId: 'supply-chain',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'recommendations.sc2.title',
    descriptionKey: 'recommendations.sc2.description',
    firstStepKey: 'recommendations.sc2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. d NIS2-RL, §30 Abs. 2 Nr. 4 BSIG',
    bsiReference: 'ORP.1, OPS.1.1.3',
  },
  // Category 5: Erwerb/Entwicklung
  {
    id: 'rec-ad-1',
    categoryId: 'acquisition-development',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'recommendations.ad1.title',
    descriptionKey: 'recommendations.ad1.description',
    firstStepKey: 'recommendations.ad1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. e NIS2-RL, §30 Abs. 2 Nr. 5 BSIG',
    bsiReference: 'OPS.1.1.3, CON.8',
  },
  {
    id: 'rec-ad-2',
    categoryId: 'acquisition-development',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'recommendations.ad2.title',
    descriptionKey: 'recommendations.ad2.description',
    firstStepKey: 'recommendations.ad2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. e NIS2-RL, §30 Abs. 2 Nr. 5 BSIG',
    bsiReference: 'CON.8, OPS.1.1.6',
  },
  // Category 6: Wirksamkeit
  {
    id: 'rec-ea-1',
    categoryId: 'effectiveness-assessment',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'recommendations.ea1.title',
    descriptionKey: 'recommendations.ea1.description',
    firstStepKey: 'recommendations.ea1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. f NIS2-RL, §30 Abs. 2 Nr. 6 BSIG',
    bsiReference: 'ISMS.1, ORP.5',
  },
  {
    id: 'rec-ea-2',
    categoryId: 'effectiveness-assessment',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'recommendations.ea2.title',
    descriptionKey: 'recommendations.ea2.description',
    firstStepKey: 'recommendations.ea2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. f NIS2-RL, §30 Abs. 2 Nr. 6 BSIG',
    bsiReference: 'ISMS.1',
  },
  // Category 7: Cyberhygiene
  {
    id: 'rec-ch-1',
    categoryId: 'cyber-hygiene',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'recommendations.ch1.title',
    descriptionKey: 'recommendations.ch1.description',
    firstStepKey: 'recommendations.ch1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. g NIS2-RL, §30 Abs. 2 Nr. 7 BSIG',
    bsiReference: 'ORP.3',
  },
  {
    id: 'rec-ch-2',
    categoryId: 'cyber-hygiene',
    priority: 'medium',
    effortLevel: 'quick',
    titleKey: 'recommendations.ch2.title',
    descriptionKey: 'recommendations.ch2.description',
    firstStepKey: 'recommendations.ch2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. g NIS2-RL, §30 Abs. 2 Nr. 7 BSIG',
    bsiReference: 'ORP.3, ORP.2',
  },
  // Category 8: Kryptografie
  {
    id: 'rec-cr-1',
    categoryId: 'cryptography',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'recommendations.cr1.title',
    descriptionKey: 'recommendations.cr1.description',
    firstStepKey: 'recommendations.cr1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. h NIS2-RL, §30 Abs. 2 Nr. 8 BSIG',
    bsiReference: 'CON.1, NET.4.1',
  },
  {
    id: 'rec-cr-2',
    categoryId: 'cryptography',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'recommendations.cr2.title',
    descriptionKey: 'recommendations.cr2.description',
    firstStepKey: 'recommendations.cr2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. h NIS2-RL, §30 Abs. 2 Nr. 8 BSIG',
    bsiReference: 'CON.1',
  },
  // Category 9: Zugriffskontrolle
  {
    id: 'rec-ac-1',
    categoryId: 'access-control',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'recommendations.ac1.title',
    descriptionKey: 'recommendations.ac1.description',
    firstStepKey: 'recommendations.ac1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. i NIS2-RL, §30 Abs. 2 Nr. 9 BSIG',
    bsiReference: 'ORP.4',
  },
  {
    id: 'rec-ac-2',
    categoryId: 'access-control',
    priority: 'medium',
    effortLevel: 'quick',
    titleKey: 'recommendations.ac2.title',
    descriptionKey: 'recommendations.ac2.description',
    firstStepKey: 'recommendations.ac2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. i NIS2-RL, §30 Abs. 2 Nr. 9 BSIG',
    bsiReference: 'ORP.4, ORP.2',
  },
  // Category 10: MFA/Kommunikation
  {
    id: 'rec-mc-1',
    categoryId: 'authentication-communication',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'recommendations.mc1.title',
    descriptionKey: 'recommendations.mc1.description',
    firstStepKey: 'recommendations.mc1.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. j NIS2-RL, §30 Abs. 2 Nr. 10 BSIG',
    bsiReference: 'ORP.4, NET.4.1',
  },
  {
    id: 'rec-mc-2',
    categoryId: 'authentication-communication',
    priority: 'medium',
    effortLevel: 'quick',
    titleKey: 'recommendations.mc2.title',
    descriptionKey: 'recommendations.mc2.description',
    firstStepKey: 'recommendations.mc2.firstStep',
    legalReference: 'Art. 21 Abs. 2 lit. j NIS2-RL, §30 Abs. 2 Nr. 10 BSIG',
    bsiReference: 'ORP.4, NET.4.2',
  },
];

export function getRecommendationsByCategory(categoryId: string): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.categoryId === categoryId);
}
