/**
 * KRITIS Recommendations per Category
 *
 * Each category has 3 prioritized recommendations with concrete first steps,
 * legal references, and BSI IT-Grundschutz building block references.
 * 24 recommendations total (8 categories x 3 recommendations).
 *
 * Legal basis: §8a, §8b BSI-Gesetz; BSI-KritisV
 * BSI references: IT-Grundschutz-Kompendium Edition 2023
 */

import type { Recommendation } from './types';

export const RECOMMENDATIONS: Recommendation[] = [
  // Category 1: BSI-Kontaktstelle
  {
    id: 'rec-bsi-1',
    categoryId: 'bsi-kontaktstelle',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'kritis.recommendations.bsi1.title',
    descriptionKey: 'kritis.recommendations.bsi1.description',
    firstStepKey: 'kritis.recommendations.bsi1.firstStep',
    legalReference: '§8b Abs. 3 BSI-Gesetz',
    bsiReference: 'ORP.1',
  },
  {
    id: 'rec-bsi-2',
    categoryId: 'bsi-kontaktstelle',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'kritis.recommendations.bsi2.title',
    descriptionKey: 'kritis.recommendations.bsi2.description',
    firstStepKey: 'kritis.recommendations.bsi2.firstStep',
    legalReference: '§8b Abs. 3 BSI-Gesetz',
    bsiReference: 'ORP.1, DER.2.1',
  },
  {
    id: 'rec-bsi-3',
    categoryId: 'bsi-kontaktstelle',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.bsi3.title',
    descriptionKey: 'kritis.recommendations.bsi3.description',
    firstStepKey: 'kritis.recommendations.bsi3.firstStep',
    legalReference: '§8b Abs. 3 BSI-Gesetz',
    bsiReference: 'ORP.1',
    checklistKey: 'kritis.recommendations.bsi3.checklist',
  },

  // Category 2: IT-Risikomanagement
  {
    id: 'rec-rm-1',
    categoryId: 'risikomanagement',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.rm1.title',
    descriptionKey: 'kritis.recommendations.rm1.description',
    firstStepKey: 'kritis.recommendations.rm1.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'BSI-Standard 200-3, ISMS.1',
  },
  {
    id: 'rec-rm-2',
    categoryId: 'risikomanagement',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.rm2.title',
    descriptionKey: 'kritis.recommendations.rm2.description',
    firstStepKey: 'kritis.recommendations.rm2.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'ISMS.1, ORP.1',
  },
  {
    id: 'rec-rm-3',
    categoryId: 'risikomanagement',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'kritis.recommendations.rm3.title',
    descriptionKey: 'kritis.recommendations.rm3.description',
    firstStepKey: 'kritis.recommendations.rm3.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'BSI-Standard 200-2, ISMS.1',
    checklistKey: 'kritis.recommendations.rm3.checklist',
  },

  // Category 3: Vorfallmanagement
  {
    id: 'rec-vm-1',
    categoryId: 'vorfallmanagement',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.vm1.title',
    descriptionKey: 'kritis.recommendations.vm1.description',
    firstStepKey: 'kritis.recommendations.vm1.firstStep',
    legalReference: '§8b Abs. 4 BSI-Gesetz',
    bsiReference: 'DER.2.1, BSI-Standard 100-4',
  },
  {
    id: 'rec-vm-2',
    categoryId: 'vorfallmanagement',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'kritis.recommendations.vm2.title',
    descriptionKey: 'kritis.recommendations.vm2.description',
    firstStepKey: 'kritis.recommendations.vm2.firstStep',
    legalReference: '§8b Abs. 4 BSI-Gesetz',
    bsiReference: 'DER.2.1, DER.2.2',
  },
  {
    id: 'rec-vm-3',
    categoryId: 'vorfallmanagement',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.vm3.title',
    descriptionKey: 'kritis.recommendations.vm3.description',
    firstStepKey: 'kritis.recommendations.vm3.firstStep',
    legalReference: '§8b Abs. 4 BSI-Gesetz',
    bsiReference: 'DER.2.1, DER.2.3',
    checklistKey: 'kritis.recommendations.vm3.checklist',
  },

  // Category 4: BCM
  {
    id: 'rec-bcm-1',
    categoryId: 'bcm',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.bcm1.title',
    descriptionKey: 'kritis.recommendations.bcm1.description',
    firstStepKey: 'kritis.recommendations.bcm1.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'CON.3, BSI-Standard 200-4',
  },
  {
    id: 'rec-bcm-2',
    categoryId: 'bcm',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.bcm2.title',
    descriptionKey: 'kritis.recommendations.bcm2.description',
    firstStepKey: 'kritis.recommendations.bcm2.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'DER.4, BSI-Standard 200-4',
  },
  {
    id: 'rec-bcm-3',
    categoryId: 'bcm',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'kritis.recommendations.bcm3.title',
    descriptionKey: 'kritis.recommendations.bcm3.description',
    firstStepKey: 'kritis.recommendations.bcm3.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'BSI-Standard 200-4, CON.3',
    checklistKey: 'kritis.recommendations.bcm3.checklist',
  },

  // Category 5: Lieferkette
  {
    id: 'rec-lk-1',
    categoryId: 'lieferkette',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'kritis.recommendations.lk1.title',
    descriptionKey: 'kritis.recommendations.lk1.description',
    firstStepKey: 'kritis.recommendations.lk1.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'ORP.1',
  },
  {
    id: 'rec-lk-2',
    categoryId: 'lieferkette',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.lk2.title',
    descriptionKey: 'kritis.recommendations.lk2.description',
    firstStepKey: 'kritis.recommendations.lk2.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'ORP.1, OPS.1.1.3',
  },
  {
    id: 'rec-lk-3',
    categoryId: 'lieferkette',
    priority: 'low',
    effortLevel: 'strategic',
    titleKey: 'kritis.recommendations.lk3.title',
    descriptionKey: 'kritis.recommendations.lk3.description',
    firstStepKey: 'kritis.recommendations.lk3.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'ORP.1, OPS.1.1.3',
    checklistKey: 'kritis.recommendations.lk3.checklist',
  },

  // Category 6: Audit
  {
    id: 'rec-au-1',
    categoryId: 'audit',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.au1.title',
    descriptionKey: 'kritis.recommendations.au1.description',
    firstStepKey: 'kritis.recommendations.au1.firstStep',
    legalReference: '§8a Abs. 3 BSI-Gesetz',
    bsiReference: 'ISMS.1, ORP.5',
  },
  {
    id: 'rec-au-2',
    categoryId: 'audit',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.au2.title',
    descriptionKey: 'kritis.recommendations.au2.description',
    firstStepKey: 'kritis.recommendations.au2.firstStep',
    legalReference: '§8a Abs. 3 BSI-Gesetz',
    bsiReference: 'ISMS.1',
  },
  {
    id: 'rec-au-3',
    categoryId: 'audit',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'kritis.recommendations.au3.title',
    descriptionKey: 'kritis.recommendations.au3.description',
    firstStepKey: 'kritis.recommendations.au3.firstStep',
    legalReference: '§8a Abs. 3 BSI-Gesetz',
    bsiReference: 'ISMS.1, ORP.5',
    checklistKey: 'kritis.recommendations.au3.checklist',
  },

  // Category 7: Physische Sicherheit
  {
    id: 'rec-ps-1',
    categoryId: 'physische-sicherheit',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.ps1.title',
    descriptionKey: 'kritis.recommendations.ps1.description',
    firstStepKey: 'kritis.recommendations.ps1.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'INF.1, INF.2',
  },
  {
    id: 'rec-ps-2',
    categoryId: 'physische-sicherheit',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.ps2.title',
    descriptionKey: 'kritis.recommendations.ps2.description',
    firstStepKey: 'kritis.recommendations.ps2.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'INF.1, INF.5',
  },
  {
    id: 'rec-ps-3',
    categoryId: 'physische-sicherheit',
    priority: 'low',
    effortLevel: 'strategic',
    titleKey: 'kritis.recommendations.ps3.title',
    descriptionKey: 'kritis.recommendations.ps3.description',
    firstStepKey: 'kritis.recommendations.ps3.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'INF.1, INF.2, INF.5',
    checklistKey: 'kritis.recommendations.ps3.checklist',
  },

  // Category 8: Systemhaertung
  {
    id: 'rec-sh-1',
    categoryId: 'systemhaertung',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.sh1.title',
    descriptionKey: 'kritis.recommendations.sh1.description',
    firstStepKey: 'kritis.recommendations.sh1.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'SYS.1.1, OPS.1.1.3',
  },
  {
    id: 'rec-sh-2',
    categoryId: 'systemhaertung',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'kritis.recommendations.sh2.title',
    descriptionKey: 'kritis.recommendations.sh2.description',
    firstStepKey: 'kritis.recommendations.sh2.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'NET.1.1, NET.1.2',
  },
  {
    id: 'rec-sh-3',
    categoryId: 'systemhaertung',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'kritis.recommendations.sh3.title',
    descriptionKey: 'kritis.recommendations.sh3.description',
    firstStepKey: 'kritis.recommendations.sh3.firstStep',
    legalReference: '§8a Abs. 1 BSI-Gesetz',
    bsiReference: 'SYS.1.1, NET.1.1, OPS.1.1.3',
    checklistKey: 'kritis.recommendations.sh3.checklist',
  },
];

export function getRecommendationsByCategory(categoryId: string): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.categoryId === categoryId);
}
