/**
 * CRA Recommendations per Category
 *
 * Each category has 3 prioritized recommendations with concrete first steps,
 * legal references, and harmonized standard references.
 * 24 recommendations total (8 categories x 3 recommendations).
 *
 * Legal basis: Verordnung (EU) 2024/2847 (Cyber Resilience Act)
 * Standard references: EN 18031-1/2/3, ETSI EN 303 645, ISO/IEC 62443
 */

import type { Recommendation } from './types';

export const RECOMMENDATIONS: Recommendation[] = [
  // Category 1: Security by Design
  {
    id: 'rec-sbd-1',
    categoryId: 'security-by-design',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.sbd1.title',
    descriptionKey: 'cra.recommendations.sbd1.description',
    firstStepKey: 'cra.recommendations.sbd1.firstStep',
    legalReference: 'Art. 10 Abs. 1 CRA, Anhang I Teil I',
    standardReference: 'EN 18031-1 Abschnitt 5',
  },
  {
    id: 'rec-sbd-2',
    categoryId: 'security-by-design',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'cra.recommendations.sbd2.title',
    descriptionKey: 'cra.recommendations.sbd2.description',
    firstStepKey: 'cra.recommendations.sbd2.firstStep',
    legalReference: 'Art. 10 Abs. 2 CRA, Anhang I Teil I Nr. 1',
    standardReference: 'EN 18031-1, OWASP ASVS',
  },
  {
    id: 'rec-sbd-3',
    categoryId: 'security-by-design',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'cra.recommendations.sbd3.title',
    descriptionKey: 'cra.recommendations.sbd3.description',
    firstStepKey: 'cra.recommendations.sbd3.firstStep',
    legalReference: 'Art. 10 Abs. 3 CRA, Anhang I Teil I Nr. 2',
    standardReference: 'IEC 62443-4-1, Microsoft SDL',
    checklistKey: 'cra.recommendations.sbd3.checklist',
  },

  // Category 2: Schwachstellenmanagement
  {
    id: 'rec-swm-1',
    categoryId: 'schwachstellenmanagement',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.swm1.title',
    descriptionKey: 'cra.recommendations.swm1.description',
    firstStepKey: 'cra.recommendations.swm1.firstStep',
    legalReference: 'Art. 11 Abs. 1-2 CRA, Anhang I Teil II',
    standardReference: 'ISO/IEC 30111, ISO/IEC 29147',
  },
  {
    id: 'rec-swm-2',
    categoryId: 'schwachstellenmanagement',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'cra.recommendations.swm2.title',
    descriptionKey: 'cra.recommendations.swm2.description',
    firstStepKey: 'cra.recommendations.swm2.firstStep',
    legalReference: 'Art. 11 Abs. 2 CRA',
    standardReference: 'ISO/IEC 29147, RFC 9116',
  },
  {
    id: 'rec-swm-3',
    categoryId: 'schwachstellenmanagement',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.swm3.title',
    descriptionKey: 'cra.recommendations.swm3.description',
    firstStepKey: 'cra.recommendations.swm3.firstStep',
    legalReference: 'Art. 11 Abs. 3 CRA, Anhang I Teil II Nr. 5',
    standardReference: 'EN 18031-1, CVE/NVD',
    checklistKey: 'cra.recommendations.swm3.checklist',
  },

  // Category 3: SBOM
  {
    id: 'rec-sbom-1',
    categoryId: 'sbom',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.sbom1.title',
    descriptionKey: 'cra.recommendations.sbom1.description',
    firstStepKey: 'cra.recommendations.sbom1.firstStep',
    legalReference: 'Art. 10 Abs. 6 CRA',
    standardReference: 'NTIA SBOM Minimum Elements, CycloneDX',
  },
  {
    id: 'rec-sbom-2',
    categoryId: 'sbom',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.sbom2.title',
    descriptionKey: 'cra.recommendations.sbom2.description',
    firstStepKey: 'cra.recommendations.sbom2.firstStep',
    legalReference: 'Art. 10 Abs. 6 CRA',
    standardReference: 'SPDX, CycloneDX, OWASP Dependency-Track',
  },
  {
    id: 'rec-sbom-3',
    categoryId: 'sbom',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'cra.recommendations.sbom3.title',
    descriptionKey: 'cra.recommendations.sbom3.description',
    firstStepKey: 'cra.recommendations.sbom3.firstStep',
    legalReference: 'Art. 10 Abs. 6 CRA',
    standardReference: 'NTIA SBOM, VEX (Vulnerability Exploitability eXchange)',
    checklistKey: 'cra.recommendations.sbom3.checklist',
  },

  // Category 4: Update-Management
  {
    id: 'rec-um-1',
    categoryId: 'update-management',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.um1.title',
    descriptionKey: 'cra.recommendations.um1.description',
    firstStepKey: 'cra.recommendations.um1.firstStep',
    legalReference: 'Art. 10 Abs. 12 CRA, Anhang I Teil I Nr. 7',
    standardReference: 'ETSI EN 303 645 Abschnitt 5.3',
  },
  {
    id: 'rec-um-2',
    categoryId: 'update-management',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'cra.recommendations.um2.title',
    descriptionKey: 'cra.recommendations.um2.description',
    firstStepKey: 'cra.recommendations.um2.firstStep',
    legalReference: 'Art. 10 Abs. 12 CRA',
    standardReference: 'EN 18031-1, ETSI EN 303 645',
  },
  {
    id: 'rec-um-3',
    categoryId: 'update-management',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.um3.title',
    descriptionKey: 'cra.recommendations.um3.description',
    firstStepKey: 'cra.recommendations.um3.firstStep',
    legalReference: 'Art. 10 Abs. 12 CRA, Anhang I Teil I Nr. 7',
    standardReference: 'ETSI EN 303 645 Abschnitt 5.3',
    checklistKey: 'cra.recommendations.um3.checklist',
  },

  // Category 5: Dokumentation
  {
    id: 'rec-dok-1',
    categoryId: 'dokumentation',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.dok1.title',
    descriptionKey: 'cra.recommendations.dok1.description',
    firstStepKey: 'cra.recommendations.dok1.firstStep',
    legalReference: 'Art. 31 CRA, Anhang VII',
    standardReference: 'EN ISO/IEC 17050-1',
  },
  {
    id: 'rec-dok-2',
    categoryId: 'dokumentation',
    priority: 'medium',
    effortLevel: 'quick',
    titleKey: 'cra.recommendations.dok2.title',
    descriptionKey: 'cra.recommendations.dok2.description',
    firstStepKey: 'cra.recommendations.dok2.firstStep',
    legalReference: 'Art. 31 CRA, Anhang VII Nr. 2',
    standardReference: 'Anhang VII CRA',
  },
  {
    id: 'rec-dok-3',
    categoryId: 'dokumentation',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.dok3.title',
    descriptionKey: 'cra.recommendations.dok3.description',
    firstStepKey: 'cra.recommendations.dok3.firstStep',
    legalReference: 'Art. 31 CRA, Anhang VII Nr. 4',
    standardReference: 'EN ISO/IEC 17050-1, Anhang VII CRA',
    checklistKey: 'cra.recommendations.dok3.checklist',
  },

  // Category 6: Vorfall-Meldepflichten
  {
    id: 'rec-vm-1',
    categoryId: 'vorfall-meldung',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.vm1.title',
    descriptionKey: 'cra.recommendations.vm1.description',
    firstStepKey: 'cra.recommendations.vm1.firstStep',
    legalReference: 'Art. 14 Abs. 1-2 CRA',
    standardReference: 'ENISA Reporting Guidelines',
  },
  {
    id: 'rec-vm-2',
    categoryId: 'vorfall-meldung',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'cra.recommendations.vm2.title',
    descriptionKey: 'cra.recommendations.vm2.description',
    firstStepKey: 'cra.recommendations.vm2.firstStep',
    legalReference: 'Art. 14 Abs. 2 CRA',
    standardReference: 'ENISA Reporting Guidelines, CSIRT Network',
  },
  {
    id: 'rec-vm-3',
    categoryId: 'vorfall-meldung',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.vm3.title',
    descriptionKey: 'cra.recommendations.vm3.description',
    firstStepKey: 'cra.recommendations.vm3.firstStep',
    legalReference: 'Art. 14 Abs. 3 CRA',
    standardReference: 'ENISA Reporting Guidelines',
    checklistKey: 'cra.recommendations.vm3.checklist',
  },

  // Category 7: Konformitaetsbewertung
  {
    id: 'rec-konf-1',
    categoryId: 'konformitaet',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.konf1.title',
    descriptionKey: 'cra.recommendations.konf1.description',
    firstStepKey: 'cra.recommendations.konf1.firstStep',
    legalReference: 'Art. 24-28 CRA, Anhang VIII',
    standardReference: 'EN ISO/IEC 17065, Anhang VIII CRA',
  },
  {
    id: 'rec-konf-2',
    categoryId: 'konformitaet',
    priority: 'medium',
    effortLevel: 'quick',
    titleKey: 'cra.recommendations.konf2.title',
    descriptionKey: 'cra.recommendations.konf2.description',
    firstStepKey: 'cra.recommendations.konf2.firstStep',
    legalReference: 'Art. 30 CRA',
    standardReference: 'CE-Kennzeichnung, Art. 30 CRA',
  },
  {
    id: 'rec-konf-3',
    categoryId: 'konformitaet',
    priority: 'medium',
    effortLevel: 'strategic',
    titleKey: 'cra.recommendations.konf3.title',
    descriptionKey: 'cra.recommendations.konf3.description',
    firstStepKey: 'cra.recommendations.konf3.firstStep',
    legalReference: 'Art. 24-30 CRA',
    standardReference: 'EN ISO/IEC 17065, EU-Typenpruefung',
    checklistKey: 'cra.recommendations.konf3.checklist',
  },

  // Category 8: Support & Lebenszyklus
  {
    id: 'rec-sl-1',
    categoryId: 'support-lifecycle',
    priority: 'high',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.sl1.title',
    descriptionKey: 'cra.recommendations.sl1.description',
    firstStepKey: 'cra.recommendations.sl1.firstStep',
    legalReference: 'Art. 10 Abs. 12 CRA',
    standardReference: 'IEC 62443-4-1, EN 18031-1',
  },
  {
    id: 'rec-sl-2',
    categoryId: 'support-lifecycle',
    priority: 'high',
    effortLevel: 'quick',
    titleKey: 'cra.recommendations.sl2.title',
    descriptionKey: 'cra.recommendations.sl2.description',
    firstStepKey: 'cra.recommendations.sl2.firstStep',
    legalReference: 'Art. 10 Abs. 12 CRA',
    standardReference: 'ETSI EN 303 645 Abschnitt 5.3',
  },
  {
    id: 'rec-sl-3',
    categoryId: 'support-lifecycle',
    priority: 'medium',
    effortLevel: 'medium',
    titleKey: 'cra.recommendations.sl3.title',
    descriptionKey: 'cra.recommendations.sl3.description',
    firstStepKey: 'cra.recommendations.sl3.firstStep',
    legalReference: 'Art. 10 Abs. 12 CRA',
    standardReference: 'IEC 62443-4-1, EN 18031-1',
    checklistKey: 'cra.recommendations.sl3.checklist',
  },
];

export function getRecommendationsByCategory(categoryId: string): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.categoryId === categoryId);
}
